#!/usr/bin/expect
set timeout -1
spawn nohup python clone_repos.py /export/repos/0/
spawn nohup python clone_repos.py /export/repos/1/
spawn nohup python clone_repos.py /export/repos/2/
spawn nohup python clone_repos.py /export/repos/3/
expect {           
  "Username for 'https://bitbucket.org':" {
      send "\r"
      exp_continue
  } 
  "Password for 'https://bitbucket.org':" {
      send "\r"
      exp_continue
  }
}
