#!/usr/bin/expect
set timeout -1
spawn python clone_repos.py /export/repos/2/
expect {           
  "Username for 'https://bitbucket.org':" {
      send "\r"
      exp_continue
  }
  "Password for 'https://bitbucket.org':" {
      send "\r"
      exp_continue
  }
  "user:" {
      send "\004"
      exp_continue
  }
  "password:" {
      send "\004"
      exp_continue
  }
}
